# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0165e587b500ac18cc056ad15e39fffe27f1364f34e2a36819116f16c08e9b2c48534895493413ed91a60ee7fed1cadbaf56bb6c0c65c8c8616c2e814d86fa5

test:
  secret_key_base: b316e907d4d4330df0f36e64d14282438d5cabe682bcb7355ce1fce57fc412cd7153dd96be1fbf5fd9bfb86d8dcbc0a87e4dc249dc698e4fcbaf73f7961dbb38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
